### ISSUE TITLE
Feature suggestion: config file

### ISSUE THREAD

**Issue by vict0rsch** [mila-iqia/milatools#92]
Would be great to specify an identifier (like a project name or something) to map a project to a path, possibly per cluster. Something like 

```yaml
# ~/.milatools.yaml
myproject:
	mila: /home/mila/s/schmidtv/project/code/repos/repoName
	beluga: /home/vsch/scratch/project/repos/repoName
	
myproject2:
	mila: /home/mila/s/schmidtv/thatthing/foo/proj2
	beluga: /home/vsch/scratch/thatotherthing/bar/proj2-github
```

and then specify an identifier or project with `-p myproject2` (or `-i myproject2`)

--- 

You could even push this feature further to be more complex and precise with alloc defaults

```yaml
# ~/.milatools.yaml
myproject:
	mila: 
		path: /home/mila/s/schmidtv/project/code/repos/repoName
		alloc:
			cpus: 2
			memory: 12G
	beluga: 
		path: /home/vsch/scratch/project/repos/repoName
```

And potentially overwrite defaults with something like `--remember-alloc`
